CREATE TABLE [dbo].[Student]
(
	[Id] INT IDENTITY(1,1),
	[FirstName] VARCHAR(50) NOT NULL,
	[LastName] VARCHAR(50) NOT NULL,
	[BirthDate] DATETIME NOT NULL,
	[YearResult] INT NOT NULL,
	[SectionID] INT NOT NULL,
	[Active] BIT NOT NULL DEFAULT 1,

	CONSTRAINT [PK_STUDENT_ID] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_STUDENT_SECTION] FOREIGN KEY ([SectionID]) REFERENCES [Section]([Id]) ,
	CONSTRAINT [CK_STUDENT_YEARRESULT] CHECK ([YearResult] BETWEEN 0 AND 20),
	CONSTRAINT [CK_STUDENT_BIRTHDATE] CHECK (DATEDIFF(DAY, '1930-01-01', [BirthDate]) > 0)

)

GO

CREATE TRIGGER [dbo].[TR_STUDENT_ONDELETE]
    ON [dbo].[Student]
    INSTEAD OF DELETE
    AS
    BEGIN
        SET NoCount ON
		UPDATE [Student]
		SET  [Active] = 0
		WHERE [Id] = (SELECT [Id] FROM deleted)
    END